const{test, expect} = require("@playwright/test");

test("Playwright Special Locator", async ({page})=>{
    await page.goto("https://rahulshettyacademy.com/angularpractice/");
    await page.locator("label+[name='name']").fill("Mitrabhanu Pradhan");
    await page.getByPlaceholder("Password").fill("Kuna@3456");
    await page.getByLabel("Check me out if you Love IceCreams!").click();
    await page.getByLabel("Gender").selectOption("Male");
    await page.getByLabel("Student").click();

    await page.getByRole("button",{name: "Submit"}).click();

    //5 Seconds timeout for expect assertions
    await expect(page.getByText("The Form has been submitted successfully!.")).toBeVisible({timeout: 10_000});

    await page.getByRole("link",{name:"Shop"}).click();
    await page.locator("app-card").filter({hasText: 'Nokia Edge'}).getByRole("button").click();

    
});

//30 seconds - test timeout error
test("Playwright Test Level Timeout", async ({page})=>{
    //Test level Timeout
    test.setTimeout(60000);
    const slowExpect= expect.configure({timeout:12_000});
    //Test Level action timeout
    page.setDefaultTimeout(9000);
    await page.goto("https://rahulshettyacademy.com/angularpractice/");
    await page.locator("label+[name='name']").fill("Mitrabhanu Pradhan");
    await page.getByPlaceholder("Password").fill("Kuna@3456");
    await page.getByLabel("Check me out if you Love IceCreams!").click();
    await page.getByLabel("Gender").selectOption("Male");
    await page.getByLabel("Student").click();

    await page.getByRole("button",{name: "Submit"}).click();

    //5 Seconds timeout for expect assertions
    await slowExpect(page.getByText("The Form has been submitted successfully!.")).toBeVisible();

    //Global Label Timeout-> test ->step level action timeout
    await page.getByRole("link",{name:"Shop"}).click({timeout:15000});

    await slowExpect(page.locator(".my-4").first()).toHaveText("Shop Name");

    await page.locator("app-card").filter({hasText: 'Nokia Edge'}).getByRole("button").click();

    
});

test('Code Generated By Code Gen', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/angularpractice/');
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.locator('app-card').filter({ hasText: 'iphone X $24.99 Lorem ipsum' }).getByRole('button').click();
  await page.locator('app-card').filter({ hasText: 'Samsung Note 8 $24.99 Lorem' }).getByRole('button').click();
  await expect(page.getByRole('heading', { name: 'Shop Name' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Shop Name' })).toBeVisible();
  await expect(page.locator('h1')).toContainText('Shop Name');
  await page.getByText('Checkout ( 2 ) (current)').click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await expect(page.getByText('Please choose your delivery')).toBeVisible();
  await expect(page.locator('app-checkout')).toContainText('Please choose your delivery location. Then click on purchase button');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).click();
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).pressSequentially('India');
  await page.getByText('India').click();
  await expect(page.getByRole('textbox', { name: 'Please choose your delivery' })).toHaveValue('India');
  await page.getByRole('textbox', { name: 'Please choose your delivery' }).click();
  await expect(page.getByRole('textbox', { name: 'Please choose your delivery' })).toHaveValue('India');
  await page.getByText('I agree with the term &').click();
  await page.getByRole('checkbox', { name: 'I agree with the term &' }).check();
  await page.getByRole('button', { name: 'Purchase' }).click();
  await page.getByText('× Success! Thank you! Your').click();
  await expect(page.getByText('× Success! Thank you! Your')).toBeVisible();
  await expect(page.locator('app-checkout')).toContainText('× Success! Thank you! Your order will be delivered in next few weeks :-).');
});